### ISSUE TITLE
Fehlermeldung bei ePub Download

### ISSUE THREAD

**Issue by victorsavu3** [blaetter/blaetter_export_epub#2]
Bei Download der ePub variante einer Ausgabe tritt ein Fehler auf. PDF funktioniert einwandfrei. Ich habe Mai, August und September probiert, alle zeigen die gleiche Fehlermeldung.

![image](https://github.com/blaetter/blaetter_export_epub/assets/1961916/a084292b-23f0-4b3d-a463-987653ffab67)

**Comment by ambo** [comment]
Hi und Danke für das Ticket. Wir können den Fehler leider nicht nachvollziehen und bräuchten etwas mehr Hintergrundinfos (insb. welchen Account das betrifft). Bitte mal unter webmaster@blaetter.de anfragen mit Verweis auf dieses Ticket, dann können wir per Mail kommunizieren.

Danke!

**Comment by ambo** [comment]
issue solved.
